[pytest]
DJANGO_SETTINGS_MODULE = web.config.settings.test
python_files = tests.py test_*.py *_tests.py
pythonpath = . web
addopts = --strict-markers -m "not validate_targets"
markers =
    online: mark tests are requiring internet access.
    validate_targets: mark tests for sweeping manifest validation (sends many requests).
    validate_targets_fp: validate_targets, false positive tests only.
    validate_targets_fn: validate_targets, false negative tests only.
